#' @title Select Models (Parameter Tables)
#'
#' @description Helper functions to
#' select models (parameter tables) based on
#' various criteria.
#'
#' @return
#' Each of the select functions, by default,
#' returns a list of parameter tables (models)
#' that meet the criterion of that function,
#' or a list of plots of the parameter tables
#' if `partables` is the output of [partables_plots()].
#' If `output` is set to `"logical"`,
#' each of these functions returns
#' a logical vector to indicate models or plots
#' that meet the criterion. The vector
#' can then be used to extract objects meeting
#' the criterion.
#'
#' @name partable_select
NULL

#' @details
#'
#' The select functions can be used both
#' for a list of models in the form
#' of parameter tables (the output
#' of [lavaan::parameterTable()]) or
#' a list of plots based on these models,
#' generated by [partables_plots()].
#' They return an object of the same type.
#' Therefore, they can be used to filter
#' both models and plots of models.
#'
#' ## Select by free parameters
#'
#' The function
#' [have_pars_all()] selects models
#' that have all the free parameters
#' specified in `pars`.
#'
#' @param partables A list of parameter
#' tables, such as a
#' `partables` or `eq_partables` object.
#' It can also be the output of
#' [partables_plots()].
#'
#' @param pars A character vector
#' of `lavaan` model syntax that
#' can be converted to a parameter table.
#' It can be a vector of parameters,
#' such as `c("y ~ x", "m ~~ x")`, but
#' can also be of other forms as long
#' as `lavaan::lavParseModelString()`
#' can process it. Covariances such as
#' `"m ~~ x"` and `"x ~~ m"` are treated
#' as the same and so only one of them
#' is necessary.
#'
#' @param output The type of output.
#' If `"models"` or `"partables"`,
#' the output is a subset of the `partables`, which
#' can be a list of parameter tables
#' or a list of plots of parameter tables.
#' If `"logical"`, a
#' logical vector of the same length as
#' `partables` is returned to indicate
#' models that match the selection
#' criteria.
#'
#' @examples
#'
#' library(lavaan)
#'
#' # Model 1
#'
#' mod1 <-
#' "
#' fx =~ x1 + x2 + x3
#' fm =~ m1 + m2 + m3
#' fy =~ y1 + y2 + y3
#' fm ~ fx
#' fy ~ fm + fx
#' "
#' fit1 <- sem(
#'           model = mod1,
#'           data = data_test_3_factor_3_item
#'         )
#' fit1_1_more <- drop_k(fit1)
#' fit1_1_more_1_less <- lapply(
#'   fit1_1_more,
#'   add_k
#' )
#'
#' partables1 <- combine_partables(fit1_1_more_1_less)
#' partables1
#'
#' # === have_pars_all ====
#'
#' have_pars_all(partables1, c("fx ~~ fm", "fy ~ fx"))
#' have_pars_all(partables1, c("fx ~~ fm", "fy ~ fx"),
#'               output = "logical")
#'
#' @rdname partable_select
#' @export
have_pars_all <- function(
  partables,
  pars = NULL,
  output = c("models", "partables", "logical")
) {
  output <- match.arg(output)
  tmp <- fix_select_object(
    object = partables,
    output = output
  )
  partables <- tmp$partables
  plots_org <- tmp$plots_org
  output_tmp <- tmp$output_tmp

  out0 <- have_pars(
    partables = partables,
    pars = pars,
    mode = "all",
    output = output_tmp
  )
  out <- fix_select_output(
    out_original = out0,
    plots_org = plots_org,
    output = output
  )
  out
}

#' @details
#'
#' The function
#' [have_pars_any()] identifies models
#' that have any of the free parameters
#' specified in `pars`.
#'
#' @examples
#'
#' # === have_pars_any ====
#'
#' have_pars_any(partables1, c("fx ~~ fm", "fm ~ fx"))
#' have_pars_any(partables1, c("fx ~~ fm", "fm ~ fx"),
#'               output = "logical")
#'
#' @rdname partable_select
#' @export
have_pars_any <- function(
  partables,
  pars = NULL,
  output = c("models", "partables", "logical")
) {
  output <- match.arg(output)
  tmp <- fix_select_object(
    object = partables,
    output = output
  )
  partables <- tmp$partables
  plots_org <- tmp$plots_org
  output_tmp <- tmp$output_tmp

  out0 <- have_pars(
    partables = partables,
    pars = pars,
    mode = "any",
    output = output_tmp
  )
  out <- fix_select_output(
    out_original = out0,
    plots_org = plots_org,
    output = output
  )
  out
}

#' @details
#'
#' The function
#' [have_pars_none()] identifies models
#' that have none of the free parameters
#' specified in `pars`.
#'
#' @examples
#'
#' # === have_pars_none ====
#'
#' have_pars_none(partables1, c("fx ~~ fm", "fm ~ fx"))
#' have_pars_none(partables1, c("fx ~~ fm", "fm ~ fx"),
#'                output = "logical")
#'
#' @rdname partable_select
#' @export
have_pars_none <- function(
  partables,
  pars = NULL,
  output = c("models", "partables", "logical")
) {
  output <- match.arg(output)
  tmp <- fix_select_object(
    object = partables,
    output = output
  )
  partables <- tmp$partables
  plots_org <- tmp$plots_org
  output_tmp <- tmp$output_tmp

  out0 <- have_pars(
    partables = partables,
    pars = pars,
    mode = "none",
    output = output_tmp
  )
  out <- fix_select_output(
    out_original = out0,
    plots_org = plots_org,
    output = output
  )
  out
}

#' @noRd
have_pars <- function(
  partables,
  pars = NULL,
  mode = c("any", "all", "none"),
  output = c("models", "partables", "logical")
) {
  # Which models in the list:
  # - has any/all/none of the parameters?
  mode <- match.arg(mode)
  mode_none <- FALSE
  if (mode == "none") {
    mode <- "any"
    mode_none <- TRUE
  }
  output <- match.arg(output)
  if (output == "models") {
    output <- "partables"
  }

  tmp <- fix_select_object(
    object = partables,
    output = output
  )
  partables <- tmp$partables
  plots_org <- tmp$plots_org
  output_tmp <- tmp$output_tmp

  if (!is.null(pars)) {
    pars_lav_list <- parse_pars_to_list(pars)
    out <- sapply(
      partables,
      has_pars_i,
      pars_lav_list = pars_lav_list,
      mode = mode
    )
    if (mode_none) {
      out <- !out
    }
  } else {
    out <- rep(TRUE, length(partables))
    names(out) <- names(partables)
  }
  out1 <- switch(
    output_tmp,
    logical = out,
    partables = partables[out]
  )
  out <- fix_select_output(
    out_original = out1,
    plots_org = plots_org,
    output = output
  )
  out
}

#' @noRd
parse_pars_to_list <- function(
  pars
) {
  # Convert model syntax to a list of one-row parameter tables
  pars_lav <- lavaan::lavParseModelString(
    pars,
    as.data.frame. = TRUE,
    warn = FALSE
  )
  pars_lav_list <- split(
    pars_lav,
    seq_len(nrow(pars_lav))
  )
  pars_lav_list
}

#' @noRd
has_pars_i <- function(
  partable,
  pars_lav_list,
  mode = c("any", "all")
) {
  # Does a model have any/all of parameter pars?
  mode <- match.arg(mode)
  out0 <- sapply(
    pars_lav_list,
    has_par_i,
    partable = partable
  )
  if (mode == "any") {
    out1 <- any(out0)
  } else if (mode == "all") {
    out1 <- all(out0)
  }
  out1
}

#' @noRd
has_par_i <- function(
  partable,
  par
) {
  # Does a model have parameter par as a free parameter?
  # partable is a parameter table of a model
  # par must be a one-row parameter table
  op <- par$op
  if (op == "~~") {
    i1 <- (partable$op == par$op) &
          (partable$lhs == par$lhs) &
          (partable$rhs == par$rhs) &
          (partable$free > 0)
    i2 <- (partable$op == par$op) &
          (partable$lhs == par$rhs) &
          (partable$rhs == par$lhs) &
          (partable$free > 0)
    out <- any(i1 | i2)
  } else {
    i1 <- (partable$op == par$op) &
          (partable$lhs == par$lhs) &
          (partable$rhs == par$rhs) &
          (partable$free > 0 )
    out <- any(i1)
  }
  isTRUE(out)
}

#' @details
#'
#' ## Select by covariances with an error term
#'
#' The function [remove_x_y_ecov()]
#' removes models from `partables` that
#' have a covariance between
#' an observed or latent variable
#' (or its error term) and the error
#' term of another variable it predicts,
#' either directly or indirectly.
#'
#' @param cl A cluster created by
#' [parallel::makeCluster()]. Used
#' internally. Do not set this argument.
#'
#' @rdname partable_select
#' @export
remove_x_y_ecov <- function(
  partables,
  output = c("models", "partables", "logical"),
  cl = NULL
) {
  output <- match.arg(output)
  tmp <- fix_select_object(
    object = partables,
    output = output
  )
  partables <- tmp$partables
  plots_org <- tmp$plots_org
  output_tmp <- tmp$output_tmp

  # chk <- sapply(
  #           partables,
  #           has_x_y_ecov
  #         )
  if (!is.null(cl)) {
    chk <- parallel::parSapplyLB(
      cl = cl,
      partables,
      has_x_y_ecov2
    )
  } else {
    chk <- sapply(
              partables,
              has_x_y_ecov2
            )
  }
  # chk <- sapply(
  #           partables,
  #           has_x_y_ecov2
  #         )
  # chk <- chk | chk2
  if (output_tmp == "logical") {
    out0 <- !chk
    names(out0) <- names(partables)
  }
  if (any(chk)) {
    tmp <- class(partables)
    out0 <- partables[!chk]
    class(out0) <- tmp
  } else {
    tmp <- class(partables)
    out0 <- partables
    class(out0) <- tmp
  }
  out <- fix_select_output(
    out_original = out0,
    plots_org = plots_org,
    output = output
  )
  out
}

#' @details
#'
#' ## Select by the role of a variable
#'
#' The function [must_not_be_y()]
#' keeps only models with selected variables
#' (observed or latent) not
#' appearing as the outcome in a
#' regression equation (indicators
#' not counted). They are
#' defined as variables not
#' in `"eqs.y"`
#' as returned by [lavaan::lavNames()].
#'
#' @param vars A character vector of
#' variables to be checked.
#'
#' @examples
#'
#' # === must_not_be_y ====
#'
#' must_not_be_y(partables1, c("fx"))
#' must_not_be_y(partables1, c("fx"),
#'               output = "logical")
#'
#'
#' @rdname partable_select
#' @export
must_not_be_y <- function(
  partables,
  vars = NULL,
  output = c("models", "partables", "logical")
) {
  output <- match.arg(output)
  tmp <- fix_select_object(
    object = partables,
    output = output
  )
  partables <- tmp$partables
  plots_org <- tmp$plots_org
  output_tmp <- tmp$output_tmp

  chk <- sapply(
            partables,
            vars_is_eqsy,
            vars = vars
          )
  chk <- !chk
  if (output_tmp == "logical") {
    out0 <- chk
    names(out0) <- names(partables)
  } else {
    out0 <- partables[chk]
    class(out0) <- class(partables)
  }

  out <- fix_select_output(
    out_original = out0,
    plots_org = plots_org,
    output = output
  )
  out
}


#' @details
#'
#' The function [must_be_y()]
#' keeps only models with selected variables
#' (observed or latent)
#' appearing as the outcome in at least one
#' regression equation (indicators
#' not counted). They are
#' defined as variables
#' in `"eqs.y"`
#' as returned by [lavaan::lavNames()].
#'
#' @examples
#'
#' # === must_be_y ====
#'
#' must_be_y(partables1, c("fm"))
#' must_be_y(partables1, c("fm"),
#'           output = "logical")
#'
#' @rdname partable_select
#' @export
must_be_y <- function(
  partables,
  vars = NULL,
  output = c("models", "partables", "logical")
) {
  output <- match.arg(output)
  tmp <- fix_select_object(
    object = partables,
    output = output
  )
  partables <- tmp$partables
  plots_org <- tmp$plots_org
  output_tmp <- tmp$output_tmp

  chk <- sapply(
            partables,
            vars_is_eqsy,
            vars = vars
          )
  if (output_tmp == "logical") {
    out0 <- chk
    names(out0) <- names(partables)
  } else {
    out0 <- partables[chk]
    class(out0) <- class(partables)
  }

  out <- fix_select_output(
    out_original = out0,
    plots_org = plots_org,
    output = output
  )
  out
}


#' @noRd
vars_is_eqsy <- function(
  partable,
  vars = NULL
) {
  i <- lavaan::lavNames(
          partable,
          type = "eqs.y"
        )
  any(vars %in% i)
}

#' @details
#'
#' ## Select by paths
#'
#' The function [must_not_have_paths()]
#' keeps only models that do not
#' have any paths, direct or indirect,
#' between selected pairs of variables.
#'
#' @param y_on_x A character vector of
#' pairs of variables, specified as
#' `"y ~ x"`, for which paths will be
#' checked.
#'
#' @examples
#'
#' # === must_not_have_paths ====
#'
#' must_not_have_paths(partables1, y_on_x = c("fx ~ fm"))
#' must_not_have_paths(partables1, y_on_x = c("fx ~ fm"),
#'                     output = "logical")
#'
#' @rdname partable_select
#' @export
must_not_have_paths <- function(
  partables,
  y_on_x = NULL,
  output = c("models", "partables", "logical")
) {
  output <- match.arg(output)
  tmp <- fix_select_object(
    object = partables,
    output = output
  )
  partables <- tmp$partables
  plots_org <- tmp$plots_org
  output_tmp <- tmp$output_tmp

  chk <- sapply(
            partables,
            has_x_to_y,
            y_on_x = y_on_x,
            mode = "any"
          )
  chk <- !chk
  if (output_tmp == "logical") {
    out0 <- chk
    names(out0) <- names(partables)
  } else {
    out0 <- partables[chk]
    class(out0) <- class(partables)
  }

  out <- fix_select_output(
    out_original = out0,
    plots_org = plots_org,
    output = output
  )
  out
}


#' @details
#'
#' The function [must_have_paths()]
#' keeps only models
#' with at least one path, direct or indirect,
#' between selected pairs of variables.
#'
#' @examples
#'
#' # === must_not_have_paths ====
#'
#' must_have_paths(partables1, y_on_x = c("fm ~ fx"))
#' must_have_paths(partables1, y_on_x = c("fm ~ fx"),
#'                 output = "logical")
#'
#' @rdname partable_select
#' @export
must_have_paths <- function(
  partables,
  y_on_x = NULL,
  output = c("models", "partables", "logical")
) {
  output <- match.arg(output)
  tmp <- fix_select_object(
    object = partables,
    output = output
  )
  partables <- tmp$partables
  plots_org <- tmp$plots_org
  output_tmp <- tmp$output_tmp

  chk <- sapply(
            partables,
            has_x_to_y,
            y_on_x = y_on_x,
            mode = "all"
          )
  if (output_tmp == "logical") {
    out0 <- chk
    names(out0) <- names(partables)
  } else {
    out0 <- partables[chk]
    class(out0) <- class(partables)
  }

  out <- fix_select_output(
    out_original = out0,
    plots_org = plots_org,
    output = output
  )
  out
}

#' @noRd
has_x_to_y <- function(
  partable,
  y_on_x,
  mode = c("any", "all")
) {
  mode <- match.arg(mode)
  out <- sapply(
    y_on_x,
    has_x_to_y_i,
    partable = partable
  )
  out <- switch(
    mode,
    any = any(out),
    all = all(out)
  )
  out
}

#' @noRd
has_x_to_y_i <- function(
  partable,
  y_on_x
) {
  y_on_x_pt <- lavaan::lavParseModelString(
            y_on_x,
            as.data.frame. = TRUE
            )
  x <- y_on_x_pt$rhs
  y <- y_on_x_pt$lhs
  fit0 <- auto_ram(
    FUN = lavaan::sem,
    model = partable,
    do.fit = FALSE,
    fixed.x = FALSE
  )
  chk1 <- tryCatch(
            suppressWarnings(manymome::all_indirect_paths(
              fit = fit0,
              x = x,
              y = y
            )),
            error = function(e) e
          )
  if (inherits(chk1, "error")) {
    i1 <- FALSE
  } else {
    i1 <- length(chk1) > 0
  }
  chk2 <- has_par_i(
    partable,
    par = y_on_x_pt
  )
  i2 <- chk2
  any(i1, i2)
}

#' @noRd
partabes_from_plots <- function(
  object
) {
  out <- lapply(
    object,
    attr,
    which = "partable",
    exact = TRUE
  )
  out
}

#' @noRd
overwrite_attributes <- function(
  object,
  source_object,
  exclude = c("names")
) {
  a_names <- names(attributes(source_object))
  b_names <- setdiff(a_names, exclude)
  if (length(b_names) == 0) {
    return(object)
  }
  for (x in b_names) {
    attr(object,
         x) <- attr(
                  source_object,
                  x,
                  exact = TRUE
                )
  }
  object
}

#' @noRd
fix_select_object <- function(
  object,
  output
) {
  if (inherits(object, "partables_plots")) {
    plots_org <- object
    partables <- partabes_from_plots(plots_org)
    if (output %in% c("models", "partables")) {
      output_tmp <- "logical"
    }
  } else {
    partables <- object
    plots_org <- NULL
    output_tmp <- output
  }
  list(partables = partables,
       plots_org = plots_org,
       output_tmp = output_tmp)
}

#' @noRd
fix_select_output <- function(
  out_original,
  plots_org,
  output
) {
  if (!is.null(plots_org)) {
    if (output %in% c("models", "partables")) {
      out <- plots_org[out_original]
      out <- overwrite_attributes(
                out,
                plots_org
              )
    } else {
      out <- out_original
    }
  } else {
    out <- out_original
  }
  out
}
